name: Build DRSuite for Windows
run-name: Build DRSuite (Win) by @${{ github.actor }}

on:
  workflow_dispatch:
  release:
    types: [created]
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
env:
  RELEASEVERSION: ${{ github.ref_name }}
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_TOKEN }}
jobs:
  build:
    permissions: write-all
    name: Build DRSuite
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ windows-latest ]
    runs-on:
      labels: [ "${{ matrix.os }}" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set environment variables for linux
        # if: runner.os == 'Windows'
        run: |
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "Package=${PWD}/DRSuite_${{ env.VERSION }}_win_x64.zip" >> $GITHUB_ENV
          
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        id: setup-matlab
        with:
          cache: false
          release: R2024b
          products: >
            MATLAB_Compiler
            Image_Processing_Toolbox
            Medical_Imaging_Toolbox
            Parallel_Computing_Toolbox
            
      - name: Compile command-line tools
        uses: matlab-actions/run-command@v2
        with:
          command: "compile_cli"

      - name: make package
        run: |
          copy LICENSE.txt bin
          copy readme.md bin
          cd ..
          zip -r "${PACKAGE}" DRSuite/bin
          
      - name: Save Binaries as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drsuite_cli-${{ env.SHA_SHORT }}
          path: bin
          overwrite: true

      - name: Test 1D Workflow (MATLAB)
        uses: matlab-actions/run-command@v2
        with:
          # startup-options: -sd packaging_tools
          command: "phantom_1d_workflow"

      - name: Test 2D Workflow (MATLAB)
        uses: matlab-actions/run-command@v2
        with:
          # startup-options: -sd packaging_tools
          command: "phantom_2d_workflow"          
          
      - name: Test 1D Workflow (Compiled)
        env:
          BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: |
          PATH="${PWD}/bin:$PATH"
          ./phantom_1d_workflow.bat

      - name: Test 2D Workflow
        env:
          BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: |
          PATH="${PWD}/bin:$PATH"
          ./phantom_2d_workflow.bat

      - name: Save Test Output as Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: Result-${{ env.SHA_SHORT }}
          path: Result
          overwrite: true

      # - name: Publish ${{ env.Package }}
      #   if: github.event_name == 'release'
      #   run: |
      #     mv cli.zip "${{ env.Package }}"
        
      - name: Publish ${{ env.Package }}
        if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.Package }}"
          tag: ${{ env.RELEASEVERSION }}       
          allowUpdates: true
