name: Build DRSuite
run-name: Build DRSuite by @${{ github.actor }}

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
env:
  RELEASEVERSION: ${{ github.ref_name }}
  VERSION: 25a
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_TOKEN }}
jobs:
  build:
    permissions: write-all
    name: Build DRSuite
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ ubuntu-22.04, macos-15-intel, macos-15 ]
    runs-on:
      labels: [ "${{ matrix.os }}" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        # if: runner.environment != 'self-hosted'
        uses: matlab-actions/setup-matlab@v2
        id: setup-matlab
        with:
          cache: false
          release: R2024b
          products: >
            MATLAB_Compiler
            Image_Processing_Toolbox
            Medical_Imaging_Toolbox
            Parallel_Computing_Toolbox
        
      - name: Set environment variables
        run: |
          echo "Package=${PWD}/cli.zip" >> $GITHUB_ENV
          echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Compile command-line tools
        uses: matlab-actions/run-command@v2
        with:
          # startup-options: -sd packaging_tools
          command: "compile_cli"
          
      - name: Save Binaries as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drsuite_cli-${{ env.SHA_SHORT }}
          path: bin
          overwrite: true

      - name: Test 1D Workflow (MATLAB)
        uses: matlab-actions/run-command@v2
        with:
          # startup-options: -sd packaging_tools
          command: "phantom_1d_workflow"

      - name: Test 2D Workflow (MATLAB)
        uses: matlab-actions/run-command@v2
        with:
          # startup-options: -sd packaging_tools
          command: "phantom_2d_workflow"          
          
      - name: Test 1D Workflow (Compiled)
        env:
          BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: |
          PATH="${PWD}/bin:$PATH"
          ./phantom_1d_workflow.sh

      - name: Test 2D Workflow
        env:
          BrainSuiteMCR: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: |
          PATH="${PWD}/bin:$PATH"
          ./phantom_2d_workflow.sh

      - name: Save Test Output as Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: Result-${{ env.SHA_SHORT }}
          path: Result
          overwrite: true

        
      - name: Publish ${{ env.Package }}
        if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.Package }}"
          tag: ${{ env.RELEASEVERSION }}       
          allowUpdates: true
